### ISSUE TITLE
Marketplace dashboard: "path not found" when refreshing page

### ISSUE THREAD

**Issue by ivanligot** [DOME-Marketplace/dome-gitops#46]
### Description
When I navigate to the marketplace page and refresh it, the URL is not found. In response, I receive the following JSON:

`{"error": "Path not found"}`

### Steps to Reproduce the Issue

1. Go to the [marketplace page](https://dome-marketplace.org).
2. Refresh the page (press F5 or use the browser's refresh button).

### Expected Behavior
The marketplace page should reload correctly without any errors.

### Actual Behavior
After refreshing the marketplace page, the URL is not found and I receive a JSON error response.

**Comment by intentodepirata** [comment]
I fix that in dome-certification frontpage with a redirects all to /index.html on nginx config

Create a file on root of your Angular application, "nginx.conf" and paste code below

---Change the port of your container expose --
`server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;

    location = /index.html {
        add_header Cache-Control "no-store";
    }

    gzip on;
    gzip_types text/plain application/javascript text/css application/json application/vnd.ms-fontobject font/ttf font/otf font/opentype image/svg+xml;
}
`

Then add this line to your DockerFile
`COPY nginx.conf /etc/nginx/conf.d/default.conf`

I hope this fixs work for you.
